### ISSUE TITLE
change packaging per PyPA recommendation 

### ISSUE THREAD

**Issue by prjemian** [data-exchange/data-exchange#2]
see these references

* http://packaging.python.org/en/latest/ - latest recommendations
* https://github.com/pypa - links to various resources
* https://bitbucket.org/pypa/setuptools

**Comment by decarlof** [comment]
Pete I am working on a full new release for this package moving the data exchange definition and r/w utilities to https://github.com/data-exchange/dxfile. I will push this out in the next two weeks

**Comment by prjemian** [comment]
I closed the issue because I thought this matter had gone stale. 
Re-open if it is appropriate.
